version: '3.0'

services:
  db:
    container_name: davehakkens_database
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    container_name: davehakkens_wordpress
    depends_on:
      - db
    build: .
    volumes:
      - wp_data:/var/www/html
      - ./theme/:/var/www/html/wp-content/themes/davehakkens
    ports:
      - "8001:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

  phpmyadmin:
    container_name: davehakkens_phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    restart: always
    ports:
      - "8002:80"
    environment:
     - PMA_ARBITRARY=1

volumes:
  db_data:
  wp_data:
